syntax = "proto3";
package location;

service LocationService {
    rpc updateLocation(UpdateLocationRequest) returns (UpdateLocationResponse);
    rpc getNearbyDrivers(GetNearbyDriversRequest) returns (GetNearbyDriversResponse);
}

message UpdateLocationRequest {
    string userId = 1;
    string latitude = 2;
    string longitude = 3;
}
message UpdateLocationResponse {
    string message = 1;
}

message GetNearbyDriversRequest {
    string latitude = 1;
    string longitude = 2;
    string radius = 3;
}

message Driver {
    string driverId = 1;
    string lat = 2;
    string lng = 3;
    double distance = 4;
    string status = 5;
}
message GetNearbyDriversResponse {
  repeated Driver drivers = 1;
}
