syntax = "proto3";
package location;

import "common.proto";

service LocationService {
    rpc driverOnline(DriverOnlineRequest) returns (DriverOnlineResponse);
    rpc driverOffline(DriverOfflineRequest) returns (DriverOfflineResponse);
    rpc getNearbyDrivers(GetNearbyDriversRequest) returns (GetNearbyDriversResponse);
}

message DriverOfflineRequest {
    string driverId = 1;
}

message DriverOfflineResponse {
    string message = 1;
}

message DriverOnlineRequest {
    string userId = 1;
    LatLng location = 2;
}

message DriverOnlineResponse {
    string message = 1;
}

message GetNearbyDriversRequest {
    double latitude = 1;
    double longitude = 2;
    double radius = 3;
}

message GetNearbyDriversResponse {
    repeated string driverIds = 1;
}
