syntax = "proto3";
package ride_matching;
import "location.proto";
service RideMatchingService {
    rpc requestRide(RequestRideRequest) returns (RequestRideResponse);
    rpc calcultateRide(CalculateRideRequest) returns (CalculateRideResponse);
    rpc getRideDetails(GetRideDetailsRequest) returns (GetRideDetailsResponse);
}

message LatLng {
    double lng = 1;
    double lat = 2;
}
message Ride {
    string id = 1;
    string status = 2;
    double price = 3;
    LatLng pickupLocation = 4;
    LatLng destinationLocation = 5;
}

message CalculateRideRequest {
    LatLng pickupLocation = 1;
    LatLng destinationLocation = 2;
}
message CalculateRideResponse {
    double distance = 1;
    double duration = 2;
    double price = 3;
    repeated LatLng routeCoordinates = 4;
}
message RequestRideRequest {
    string userId = 1;
    LatLng pickupLocation = 2;
    LatLng destinationLocation = 3;
}

message RequestRideResponse {
    string message = 1;
}

message GetRideDetailsRequest {
    string rideId = 1;
}
message GetRideDetailsResponse {
    Ride ride = 1;
}