syntax = "proto3";
package ride_matching;
import "location.proto";
service RideMatchingService {
    rpc requestRide(RequestRideRequest) returns (RequestRideResponse);
}

message RequestRideRequest {
    string userId = 1;
    map<string, double> pickupLocation = 2;
    map<string, double> destinationLocation = 3;
}

message RequestRideResponse {
    string rideId = 1;
    map<string, double> pickupLocation = 2;
    map<string, double> destinationLocation = 3;
    double ridePrice = 4;
    repeated Driver nearbyDrivers = 5;
}