syntax = "proto3";
package user;

message GoogleLoginRequest {
    string code = 1;
    string ipAddress = 2;
    string userAgent = 3;
}

message GoogleLoginResponse {
    string message = 1;
    string sessionId = 2;
}

message ValidateSessionRequest {
    string sessionId = 1;
}

message ValidateSessionResponse {
    string userId = 1;
    string sessionId = 2;

}

message InvalidateSessionRequest {
    string sessionId = 1;
}

message InvalidateSessionResponse {
    string message = 1;
}

message InvalidateAllSessionsRequest {
    string userId = 1;
}

message InvalidateAllSessionsResponse {
    string message = 1;
}

service AuthService {
    rpc googleLogin(GoogleLoginRequest) returns (GoogleLoginResponse);
    rpc validateSession(ValidateSessionRequest) returns (ValidateSessionResponse);
    rpc invalidateSession(InvalidateSessionRequest) returns (InvalidateSessionResponse);
    rpc invalidateAllSessions(InvalidateAllSessionsRequest) returns (InvalidateAllSessionsResponse);
}

message UpdateUserRoleRequest {
    string userId = 1;
    string role = 2;
}

message UpdateUserRoleResponse {
    string message = 1;
}
service UserService {
    rpc updateUserRole(UpdateUserRoleRequest) returns (UpdateUserRoleResponse);
}